name = "nozil-portfolio"
compatibility_date = "2024-09-09"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "dist"

[[kv_namespaces]]
binding = "CONTACT"
id = "f39e1a50ac3048648f1c7ba55eb807e4"
